ask_cherkasov/ask_cherkasov/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from ask_cherkasov import views, settings, ajax_urls

urlpatterns = [
  url(r'^admin/', admin.site.urls, name="admin"),
  url(r'^base/', views.base, name="base"),
  url(r'^$', views.newest, name="questions-new"),
  url(r'^hot/', views.hottest, name="questions-hot"),
  url(r'^tag/(?P<tag>.+)/', views.by_tag, name="tag"),
  url(r'^question/(?P<id>\d+)/', views.question, name="question"),
  url(r'^ask/', views.ask, name="ask"),
  url(r'^login/', views.login, name="sign-in"),
  url(r'^logout/', views.logout, name="sign-out"),
  url(r'^signup/', views.signup, name="sign-up"),
  url(r'^edit/', views.edit, name="profile-edit"),
  url(r'^hello_world/', views.hello_world, name="hello-world-sample"),
  url(r'^ajax/', include(ajax_urls)),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ask_cherkasov/ask_cherkasov/models.py
# -*- coding: utf-8/ -*-

from django.db import models
from django.contrib.auth.models import User

import datetime
from django.utils import timezone
from django.db.models import Count, Sum

from django.core.urlresolvers import reverse

from random import choice
from ask_cherkasov import settings, miscellaneous, mod_ajax
from django.core.cache import cache

import os

#-- Extended user model --#

class UserData(models.Model):
  user = models.OneToOneField(User)
  avatar = models.ImageField(upload_to = 'avatars')
  about = models.TextField()

  def avatar_url(self):
    if self.avatar and hasattr(self.avatar, 'url'):
      return self.avatar.url
    else:
      return os.path.join(settings.MEDIA_URL, 'avatars', 'user-noavatar.gif')

  def __str__(self):
    return "[" + str(self.user.id) + "] " + self.user.username

#-- Extended user model end --#

#-- Tags --#

#---- Tags manager ----#

class TagManager(models.Manager):
  def questions_count(self):
    return self.annotate(questions_count = Count('question'))

  def order_by_questions_count(self):
    return self.questions_count().order_by('-questions_count')

  def by_tag(self, tag):
    return self.get(tag = tag)

  def get_or_create(self, tag):
    try:
      tag_obj = self.by_tag(tag)
    except Tag.DoesNotExist:
      tag_obj = self.create(tag = tag, colors = choice(Tag.COLORS)[0])
    return tag_obj

  def get_top_X(self, top_size=10):
    real_top = top_size
    return self.order_by_questions_count().all()[:real_top]

#---- Tags manager end ----#

#---- Tags model ----#

class Tag(models.Model):
  GREEN = 'success'
  DBLUE = 'primary'
  BLACK = 'default'
  RED = 'danger'
  LBLUE = 'info'
  COLORS = (('GR', GREEN), ('DB', DBLUE), ('B', BLACK), ('RE', RED), ('BL', LBLUE))

  tag = models.CharField(max_length=30)
  color = models.CharField(max_length=2, choices=COLORS, default=BLACK)

  objects = TagManager()

  def get_url(self):
    return reverse('tag', kwargs={'tag': self.tag})

  def __str__(self):
    return "[" + str(self.id) + "] " + self.tag

#---- Tags model end ----#

#-- Tags end --#

#-- Questions --#

#---- Querysets ----#

class QuestionQueryset(models.QuerySet):
  def with_tags(self):
    return self.prefetch_related('tags')

  def with_answers(self):
    query = self.prefetch_related('answer_set')
    query = self.prefetch_related('answer_set__author')
    query = self.prefetch_related('answer_set__author__userdata')
    return query

  def with_answers_count(self):
    return self.annotate(anscount = Count('answer__id', distinct = True))

  def with_author(self):
    return self.select_related('author').select_related('author__userdata')

  def hottest(self):
    return self.order_by('-likes')

  def with_date_later(self, date):
    return self.filter(pub_date__gt=date)

#---- Querysets end ----#

#---- Questions manager ----#

class QuestionManager(models.Manager):
  def queryset(self):
    query = QuestionQueryset(self.model, using = self._db)
    return query.with_answers_count().with_author().with_tags()

  def newest(self):
    return self.order_by('-pub_date')

  def hottest(self):
    return self.order_by('-likes')

  def by_tag(self, tag):
    return self.filter(tags = tag)

  def single(self, id):
    query = self.queryset()
    return query.with_answers().get(pk = id)

  def period_top(self, time_delta = -7):
    period_start = timezone.now() + datetime.timedelta(time_delta)
    return self.queryset().hottest().with_date_later(period_start)

#---- Questions manager end ----#

#---- Question model ----#

class Question(models.Model):
  title = models.CharField(max_length = 100)
  text = models.TextField()
  author = models.ForeignKey(User)
  pub_date = models.DateTimeField(default = timezone.now)
  tags = models.ManyToManyField(Tag)
  likes = models.IntegerField(default = 0)

  objects = QuestionManager()

  def get_url(self):
    return reverse('question', kwargs = { 'id' : self.id })

  def correct_answer(self):
    try:
      answer = Answer.objects.get(question = self, correct = True)
    except:
      answer = None
    return answer

  def __str__(self):
    return "[" + str(self.id) + "] " + self.title

  class Meta:
    ordering = ['-pub_date']

#---- Question model end ----#

#---- Likes ----#

#------ Likes manager ------#

class QuestionLikeManager(models.Manager):
  def has(self, question):
    return self.filter(question = question)

  def sum_for_question(self, question):
    return self.has(question).aggregate(sum = Sum('value'))['sum']

  def add(self, author, question, value):
    if author.id == question.author.id:
      raise QuestionLike.OwnLike
    try:
      like = self.get(author = author, question =question)
    except QuestionLike.DoesNotExist:
      like = self.create(author = author, question = question, value = value)
      question.likes = self.sum_for_question(question)
      question.save()
    else:
      raise QuestionLike.AlreadyLike

  def add_or_update(self, author, question, value):
    like, new = self.update_or_create(author = author, question = question, defaults = { 'value' : value })
    question.likes = self.sum_for_question(question)
    question.save()
    return new

#------ Likes manager end ------#

#------ Like model ------#

class QuestionLike(models.Model):
  class OwnLike(Exception):
    def __init__(self):
      super(QuestionLike.OwnLike, self).__init__('Вы не можете голосовать за собственный вопрос')

  class AlreadyLike(Exception):
    def __init__(self):
      super(QuestionLike.AlreadyLike, self).__init__('Вы уже оценили этот вопрос')

  LIKE = 1
  DISLIKE = -1

  question = models.ForeignKey(Question)
  author = models.ForeignKey(User)
  value = models.SmallIntegerField(default = LIKE)

  objects = QuestionLikeManager()

  def __str__(self):
    result = "[" + str(self.id) + "] " + self.author.username + " "
    if int(self.value) > 0:
      result += "<3"
    else:
      result += "<||3"
    result +=  " qid" + str(self.question.id)
    return result

#------ Like model end ------#

#---- Likes end ----#

#-- Questions end --#

#-- Answers --#

#---- Queryset ----#

class AnswerQueryset(models.QuerySet):
  def with_author(self):
    return self.select_related('author').select_related('author__userdata')

  def with_question(self):
    return self.select_related('question')

  def hottest(self):
    return self.order_by('-likes')

  def with_date_later(self, date):
    return self.filter(pub_date__gt = date)

#---- Queryset end ----#

#---- Manager ----#

class AnswerManager(models.Manager):
  def queryset(self):
    query = AnswerQueryset(self.model, using = self._db)
    return query.with_author()

  def create(self, **kwargs):
    answer = super(AnswerManager, self).create(**kwargs)
    text = answer.text[:100]
    if len(ans.text) > 100:
      text += '...'
    return answer

  def period_top(self, time_delta = -7):
    period_start = timezone.now() + datetime.timedelta(time_delta)
    return self.queryset().hottest().with_date_later(period_start)

#---- Manager end ----#

#---- Answer model ----#

class Answer(models.Model):
  text = models.TextField()
  question = models.ForeignKey(Question)
  author = models.ForeignKey(User)
  pub_date = models.DateTimeField(default = timezone.now)
  correct = models.BooleanField(default = False)
  likes = models.IntegerField(default = 0)

  objects = AnswerManager()

  def set_correct(self, user = None):
    question = self.question
    if user is not None and question.author.id != user.id:
      raise Exception(u'Вы не являетесь автором данного вопроса')
    current = question.correct_answer()
    if current is not None:
      current.set_incorrect()
    self.correct = True
    self.save()

  def set_incorrect(self):
    self.correct = False
    self.save()

  def __str__(self):
    "[" + str(self.id) + "] " + self.text

  class Meta:
    ordering = ['-correct', '-pub_date', '-likes']

#---- Answer model end ----#

#---- Likes ----#

#------ Likes manager ------#

class AnswerLikeManager(models.Manager):
  def has(self, answer):
    return self.filter(answer = answer)

  def sum_for_answer(self, answer):
    return self.has(answer).aggregate(sum = Sum('value'))['sum']

  def add(self, author, answer, value):
    if author.id == answer.author.id:
      raise AnswerLike.OwnLike
    try:
      like = self.get(author = author, answer = answer)
    except AnswerLike.DoesNotExist:
      like = self.create(author = author, answer = answer, value = value)
      answer.likes = self.sum_for_answer(answer)
      answer.save()
    else:
      raise AnswerLike.AlreadyLike

  def add_or_update(self, answer, author, value):
    like, new = self.update_or_create(author = author, answer = answer, defaults = { 'value' : value })
    answer.likes =self.sum_for_answer(answer)
    answer.save()
    return new

#------ Likes manager end ------#

#------ Like model ------#

class AnswerLike(models.Model):
  class OwnLike(Exception):
    def __init__(self):
      super(AnswerLike.OwnLike, self).__init__(u'Вы не можете голосовать за собственный ответ')

  class AlreadyLike(Exception):
    def __init__(self):
      super(AnswerLike.AlreadyLike, self).__init__(u'Вы уже оценили этот вопрос')

  LIKE = 1
  DISLIKE = -1

  answer = models.ForeignKey(Answer)
  author = models.ForeignKey(User)
  value = models.SmallIntegerField(default = LIKE)

  objects = AnswerLikeManager()

  def __str__(self):
    result = "[" + str(self.id) + "] " + self.author.username + " "
    if int(self.value) > 0:
      result += "<3"
    else:
      result += "<||3"
    result += " aid" + str(self.answer.id)
    return result

#------ Like model end ------#

#---- Likes end ----#

#-- Answers end --#

#-- caching --#

class AppCacher:
#---- tags caching ----#

  POPULAR_TAGS = 'tags_popular'

  @classmethod
  def get_popular_tags(self):
    return cache.get(AppCacher.POPULAR_TAGS, [])

  @classmethod
  def update_popular_tags(self):
    popular = Tag.objects.get_top_X().all()

ask_cherkasov/templates/ask.html
{% extends 'base.html' %}

{% block title %}Спросить{% endblock %}

{% block page_title %}Задать вопрос{% endblock %}

{% block content %}
  {% for err in form.non_field_errors %}
    <div class="ask-form-error">
      <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        {{ err }}
      </div>
    </div>
  {% endfor %}
  <div class="ask-form">
    <form class="form-horizontal" method="post" action="">
      {% csrf_token %}
      <div class="form-group {% if form.title.errors %}has-error{% endif %}">
        <label for="title" class="col-sm-3 control-label">{{ form.title.label }}</label>
        <div class="col-sm-6">
          {{ form. title }}
          {% if form.title.errors %}
            {% for err in form.title.errors %}
              <div class="login-form-error">
                <div class="alert alert-danger" role="alert">
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                  {{ err }}
                </div>
              </div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <div class="form-group {% if form.text.errors %}has-error{% endif %}">
        <label for="text" class="col-sm-3 control-label">{{ form.text.label }}</label>
        <div class="col-sm-6">
          {{ form.text }}
          {% if form.text.errors %}
            {% for err in form.text.errors %}
              <div class="login-form-error">
                <div class="alert alert-danger" role="alert">
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                  {{ err }}
                </div>
              </div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <div class="form-group">
        <label for="tag" class=" col-sm-3 control-label">Теги</label>
        <div class="col-sm-2">
          {{ form.tag1 }}
        </div>
        <div class="col-sm-2">
          {{ form.tag2 }}
        </div>
        <div class="col-sm-2">
          {{ form.tag3 }}
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-6">
          <button type="submit" class="btn btn-primary">Спросить!</button>
        </div>
      </div>
    </form>
  </div>

{% endblock %}

ask_cherkasov/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% block head %}
      {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Технопарк Mail.ru, первый семестр. Семестровый проект по веб-технологиям">
        <meta name="author" content="Кирилл Черкасов">
      {% endblock %}

      <title>{% block title %}{% endblock %} | AskCherkasov</title>

      {% load static %}

      {% block links %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
        <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">
        <link href="{% static 'css/alertify.bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'css/alertify.core.css' %}" rel="stylesheet">
        <link href="{% static 'css/alertify.default.css' %}" rel="stylesheet">
        <link href="{% static 'css/adjustments.css' %}" rel="stylesheet">
        <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
      {% endblock %}

      {% block head_extras %}{% endblock %}

    {% endblock %}
  </head>

  <body>
    <div class="header">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          {% block navigation %}
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Открыть меню</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'questions-new' %}">AskCherkasov</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <form class="navbar-form navbar-left" role="search">
                  <div class="form-group">
                    <input type="search" class="form-control" placeholder="Поиск">
                  </div>
                  <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-zoom-in"></span>&nbsp;Искать</button>
                </form>
                {% if request.user.is_authenticated %}
                  <li><button type="submit" class="btn btn-success navbar-btn" onclick="window.location.href='{% url 'ask' %}';">Cпросить!</button></li>
                {% endif %}
              </ul>
              <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle user-img" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      <img src="{{ request.user.userdata.avatar_url }}" class = "img-circle nav-avatar">
                      <span id="user">{{ request.user.first_name }} {{ request.user.last_name }}</span>
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'profile-edit' %}"><i class="glyphicon glyphicon-cog"></i>&nbsp;Редактировать профиль</a></li>
                      <li><a href="{% url 'sign-out' %}?continue={{ request.path }}"><i class="glyphicon glyphicon-eject"></i>&nbsp;Выйти</a></li>
                    </ul>
                  </li>
                {% else %}
                  <li><a href="{% url 'sign-in' %}"><i class="glyphicon glyphicon-user"></i>&nbsp;Войти</a></li>
                  <li><a href="{% url 'sign-up' %}"><i class="glyphicon glyphicon-plus-sign"></i>&nbsp;Зарегистрироваться</a></li>
                {% endif %}
              </ul>
            </div>
          {% endblock %}
        </div>
      </nav>
    </div>

    <div class="center-block body">
      <div class="body-content col-xs-12 col-sm-8">
        <div class="body-title">
          <div align="center"> {% block page_title %}{% endblock %} </div>
        </div>
         {%block content %}{% endblock %}
      </div>
      <div class="body-right-column col-xs-12 col-sm-3">
        <div class="body-block">
          <div class="body-block-title">
            Популярные теги
          </div>
          <div class="tags">
            {% for tag in hot_tags %}
              <a href="{{ tag.get_url }}" class="tags-tag tags-tag-{{ tag.get_color_display }}">{{ tag.tag }}</a>
            {% endfor %}
          </div>
        </div>
        <div class="body-block">
          <div class="body-block-title">
            Топ пользователей
          </div>
          <ol class="best-users">
            {% for user in best_users %}
              <li class="best-users-user">
                <span class="best-users-user-pic"></span>
                <span>&nbsp; {{ user.first_name }} {{ user.last_name }} aka {{ user.username }}</span>
              </li>
            {% endfor %}
          </ol>
        </div>
      </div>
    </div>

    <footer class="footer">
      {% block footer %}
        <div class="container" align="center">
          <p class="text-muted">&#169; Кирилл Черкасов, АПО-11, весна 2017</p>
        </div>
      {% endblock %}
    </footer>

    {% block scripts %}
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
      <script src="{% static 'js/alertify.min.js' %}"></script>
      <script src="{% static 'js/common.js' %}"></script>
    {% endblock %}
  </body>
</html>

ask_cherkasov/templates/index.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block page_title %}
    <div class="body-block">
        <p class="small">Отсортировать вопросы &nbsp; <a class="btn btn-primary" href="{% url 'questions-new' %}">По дате</a> <a class="btn btn-success" href="{% url 'questions-hot' %}">По рейтингу</a></p>
        <hr />
    </div>
{% endblock %}

{% block content %}

  {% for question in questions %}
    <div class="question question-{% if forloop.counter|divisibleby:2 %}white{% else %}grey{% endif %}">
      <div class="question-info">
        <div class="question-userpic-container">
          {% load static %}
          <img src="{{ question.author.userdata.avatar_url }}" class="userpic" title="Аватар пользователя по умолчанию" />
          <div class="small">{{ question.author.last_name }} {{ question.author.first_name }}</div>
        </div>
        <div class="question-data">
          <div class="question-title">
            <a href="{{ question.get_url }}">{{ question.title }}</a>
          </div>
          <p class="question-text">{{ question.text }}</p>
        </div>
      </div>
      <div class="question-controls">
        <div class="question-vote">
          <a class="btn btn-xs btn-danger" {% if not request.user.is_authenticated %} disabled="disabled" {% endif %} data-question-like-down="{{ question.id }}"><span class="glyphicon glyphicon-thumbs-down"></span></a>
          <span class="question-vote-count" data-question-like-count="{{ question.id }}"> {{ question.likes }} </span>
          <a class="btn btn-xs btn-success" {% if not request.user.is_authenticated %} disabled="disabled" {% endif %} data-question-like-up="{{ question.id }}"><span class="glyphicon glyphicon-thumbs-up"></span></a>
        </div>
        <div class="question-ansref">
          <a href="{{ question.get_url }}">Ответы ({{ question.anscount }})</a>
        </div>
        <div class="tags question-tags">
          {% for tag in question.tags.all %}
            <a href="{{ tag.get_url }}" class="tags-tag tags-tag-{{ tag.get_color_display }}">{{ tag.tag }}</a>
          {% endfor %}
        </div>
      </div>
    </div>
  {% endfor %}
  <div class="paginator-block" align="center">
      {% include 'paginator.html' with objects=questions %}
  </div>

{% endblock %}

ask_cherkasov/templates/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block page_title %}Вход{% endblock %}

{% block content %}
  {% for err in form.non_field_errors %}
    <div class="login-form-error">
      <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        {{ err }}
      </div>
    </div>
  {% endfor %}
  <div class="sign-in-form">
      <form class="form-horizontal" method="post" action="">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group {% if field.errors %}has-error{% endif %}">
        <label for="{{ field.name }}" class="col-sm-2 control-label">{{ field.label }}</label>
        <div class="col-sm-6">
          {{ field }}
          {% if field.errors %}
            {% for err in field.errors %}
              <div class="login-form-error">
                <div class="alert alert-danger" role="alert">
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                  {{ err }}
                </div>
              </div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      {% endfor %}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-2">
          <button type="submit" class="btn btn-primary">Войти</button>
        </div>
        <div class="col-sm-3">
          <a href="{% url 'sign-up' %}" class="btn btn-default">Регистрация</a>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

ask_cherkasov/templates/paginator.html
{% if objects.has_other_pages %}
  <nav>
    <ul class="pagination pagination-lg">
      {% if objects.has_previous %}
        <li>
          <a href="?{{ objects.key }}={{ objects.previous_page_number }}" title="Пред.">
            <span>&laquo;&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for page in objects.paginator.page_range %}
        {% if page == objects.number %}
          <li class="active">
            <span>{{ page }}</span>
          </li>
        {% elif page > objects.from_left and page < objects.from_right and page != objects.number %}
          <li>
            <a href="?{{ objects.key }}={{ page }}">
              <span>{{ page }}</span>
            </a>
          </li>
        {% endif %}
      {% endfor %}
      {% if objects.has_next %}
        <li>
          <a href="?{{ objects.key }}={{ objects.next_page_number }}" title="След.">
            <span>&raquo;&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

ask_cherkasov/templates/question.html
{% extends 'base.html' %}

{% block title %}{{ question.title }}{% endblock %}

{% block content %}
  <div class="question question-noborder">
    <div class="question-info">
      <div class="question-userpic-container">
        <img src="{{ question.author.userdata.avatar_url }}" class="userpic" title="Аватар пользователя по умолчанию" />
        <div class="small">{{ question.author.last_name }} {{ question.author.first_name }}</div>
      </div>
      <div class="question-data">
        <div class="question-title-big">
          {{ question.title }}
        </div>
        <p class="question-text">{{ question.text }}</p>
      </div>
    </div>
    <div class="question-controls">
      <div class="question-vote">
        <a class="btn btn-xs btn-danger" {% if not request.user.is_authenticated %} disabled="disabled" {% endif %} data-question-like-down="{{ answer.id }}"><span class="glyphicon glyphicon-thumbs-down"></span></a>
        <span class="question-vote-count" data-question-like-count="{{ question.id }}"> {{ question.likes }} </span>
        <a class="btn btn-xs btn-success" {% if not request.user.is_authenticated %} disabled="disabled" {% endif %} data-question-like-up="{{ question.id }}"><span class="glyphicon glyphicon-thumbs-up"></span></a>
      </div>
      <div class="tags question-tags">
        {% for tag in question.tags.all %}
          <a href="{{ tag.get_url }}" class="tags-tag tags-tag-{{ tag.get_color_display }}">{{ tag.tag }}</a>
        {% endfor %}
      </div>
    </div>
    <hr />
    <div class="answers">
      {% for answer in question.answer_set.all %}
        <div class="answer answer-{% if forloop.counter|divisibleby:2 %}white{% else %}grey{% endif %}">
          <div class="answer-info">
            <div class="answer-userpic-container">
              <img src="{{ answer.author.userdata.avatar_url }}" class="userpic" title="Аватар пользователя по умолчанию" />
              <div class="small">{{ answer.author.last_name }} {{ answer.author.first_name }}</div>
            </div>
            <div class="answer-data">
              <p class="answer-text">{{ answer.text }}</p>
            </div>
          </div>
          <div class="answer-controls">
            <div class="answer-vote">
              <a class="btn btn-xs btn-danger" {% if not request.user.is_authenticated %} disabled="disabled"{% endif %} data-answer-like-down="{{ answer.id }}"><span class="glyphicon glyphicon-thumbs-down"></span></a>
              <span class="answer-vote-count" data-answer-like-count="{{ answer.id }}"> {{ answer.likes }} </span>
              <a class="btn btn-xs btn-success" {% if not request.user.is_authenticated %} disabled="disabled"{% endif %} data-answer-like-up="{{ answer.id }}"><span class="glyphicon glyphicon-thumbs-up"></span></a>
            </div>
            <div class="answer-correct">
              <a class="btn btn-large {% if answer.correct %}answer-btn-correct{% else %}answer-btn-wrong{% endif %}" {% if question.author.id != request.user.id %}disabled="disabled"{% endif %} data-answer-correct="{{  answer.id }}"><span class="glyphicon glyphicon-ok">Правильный</span></a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <hr />
    {% if request.user.is_authenticated %}
      <div class="answer-form">
        <div class="answer-form-title">Ваш ответ</div>
        <form class="form-horizontal" method="post" action="">
          {% csrf_token %}
          <div class="form-group">
            <div class="col-sm-8">
               {{ answer_form.text }}
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-4">
              <button type="submit" class="btn btn-primary">Ответить</button>
            </div>
          </div>
        </form>
      </div>
    {% endif %}
  </div>
{% endblock %}